### PR TITLE
Fix discriminator override for kotlin

### LINKED ISSUE #1881: OpenAPI, invalid @Override annotation in base class, in inheritance case.
### Expected Behavior

Having several hierarchies of component inheritance described in the OpenAPI yml file, I want all classes to be generated correctly

### Actual Behaviour

OpenApi generator adds the `@Override` annotation in the base class, which is the foundation for the inheritance hierarchy. The problem occurs when there is more than one inheritance hierarchy in the OpenAPI's yml file. It looks like the issue arises for the first found inheritance hierarchy. 

### Steps To Reproduce

1. Create simple app 
2. Define example CRUD endpoints in OpenAPI yml file to generate API classes to implement
3. Define more than one, component inheritance hierarchy in yml file:
```
components:
  schemas:
    AnimalRequest:
      type: object
      properties:
        name:
          type: string
        valueType:
          type: string
      discriminator:
        propertyName: valueType
        mapping:
          catRq: '#/components/schemas/DogRequest'
          dogRq: '#/components/schemas/CatRequest'
    DogRequest:
      allOf:
        - $ref: '#/components/schemas/AnimalRequest'
        - type: object
      properties:
        dogProperty:
          type: string
    CatRequest:
      allOf:
        - $ref: '#/components/schemas/AnimalRequest'
        - type: object
      properties:
        catProperty:
          type: string

    AnimalResponse:
      type: object
      properties:
        name:
          type: string
        valueType:
          type: string
      discriminator:
        propertyName: valueType
        mapping:
          catRs: '#/components/schemas/DogResponse'
          dogRs: '#/components/schemas/CatResponse'
    DogResponse:
      allOf:
        - $ref: '#/components/schemas/AnimalResponse'
        - type: object
      properties:
        dogProperty:
          type: string
    CatResponse:
      allOf:
        - $ref: '#/components/schemas/AnimalResponse'
        - type: object
      properties:
        catProperty:
          type: string
```
4, `gradle compileJava` result: Generated `AnimalResponse` will contain `@Override` annotation:
```
    @Override
    public String getValueType() {
        return valueType;
    }
```
5. Problem occurse since 4.4.4
 

### Environment Information

- opensuse tumbleweed
- jdk21
- micronaut 4.7.0
- io.micronaut.openapi 4.4.4

### Example Application

https://github.com/matadini/openapi-micronaut-inheritance-bug

### Version

4.7.0

### PR DESCRIPTION
**Pull request by altro3**
Fixed #1881

The same problem for kotlin generator.

Also minor improvements for generated kotlin code

### CODE REVIEW

**Comment by altro3** [comment]
@sdelamo You're a bit hasty with the release, I fixed the problem with override in Java, but forgot about Kotlin.

In general, it would be desirable to merge this fix as well, because now the problem persists with the generator for Kotlin. Maybe release 6.13.3?

**Comment by altro3** [comment]
@sdelamo ping

**Comment by matadini** [comment]
@altro3 @sdelamo 

Hi
I'm asking here because I don't know where I could do this, so:
When do you plan to release a new version of the micronaut-gradle-plugin that will include fix https://github.com/micronaut-projects/micronaut-openapi/issues/1881? After merging kotlin fix? Or do you have any particular roadmap?

I'm asking because it is important for me from the perspective of developing an application for a client.

**Comment by altro3** [comment]
@matadini You don't need to wait for a fix for Kotlin, the fix for Java is already merged and included in the 6.13.2 release.

To use the latest version of micronaut-openapi in the gradle plugin, just write this:
```groovy
micronaut {
    openapi {
        version = "6.13.2"
        client(file("swagger.yml")) {
              ...
        }
    }
}
```

**Comment by altro3** [comment]
continue here: https://github.com/micronaut-projects/micronaut-openapi/pull/1894

**Pull request closed without merging**
