### PR TITLE
Introduce @OpenAPIInclude to process already compiled classes for OpenApi

### PR DESCRIPTION
**Pull request by dstepanov**
Allows to include additional `@Controller` and `@Endpoint` classes that are already compiled.

Fixes https://github.com/micronaut-projects/micronaut-openapi/issues/156

### CODE REVIEW

**Comment by graemerocher** [comment]
Nice, maybe an example in the docs that shows how to include the login endpoints for security would be an idea?

Also an idea could be we include a meta annotation say `@OpenApiManagement` that is annotated with `@OpenAPIInlcude` and includes all the management endpoints to make it easier to include the default ones?

**Comment by dstepanov** [comment]
Yeah, probably the same can be used for the security, I'm thinking it would be nice to support tags and security requirements on `@OpenAPIInclude`

**Comment by graemerocher** [comment]
You could probably use an `AnnotationMapper` implementation to workaround it

**Comment by dstepanov** [comment]
@graemerocher That works but any idea where to fix `AliasFor` on repeatable?

**Comment by graemerocher** [comment]
Seems to be handled here https://github.com/micronaut-projects/micronaut-core/blob/2.1.x/inject/src/main/java/io/micronaut/inject/annotation/AbstractAnnotationMetadataBuilder.java#L547

**Comment by graemerocher** [comment]
Thanks for the contribution!

**Pull request merged**
