### PR TITLE
Changes Retention Policy of openapi annotation to SOURCE

### PR DESCRIPTION
**Pull request by croudet**
so that they are not kept in micronaut generated classes.

Requires micronaut-2.x

### CODE REVIEW

**Comment by alvarosanchez** [comment]
Blocked by #223

**Comment by croudet** [comment]
@ilopmar Thanks for taking a look at that.

**Comment by ilopmar** [comment]
@croudet quick question before merging this. Is this a new feature, right? I'm asking to include it in 2.1.0 instead of 2.0.1

**Comment by croudet** [comment]
It uses `TypedAnnotationTransformer` introduced in core 2.0.0, from the openapi point of view it could be considered as a new feature.

**Comment by ilopmar** [comment]
Thanks, I'm going to update the `@since` tag to 2.1 and release a new version.

**Review by ilopmar — APPROVED** [review]

**Pull request merged**
