### PR TITLE
test: JaxRS Test

### PR DESCRIPTION
**Pull request by sdelamo**
see: https://github.com/micronaut-projects/micronaut-core/issues/4983

### CODE REVIEW

**Review by altro3 — APPROVED** [review]

**Comment by altro3** [comment]
@sdelamo I don't know, why this test failed. Maybe need to re-run CI_CD without cache.

Also, since everything is working correctly, I'm not sure that we need to add this test because it will run with each build and increase the waiting time. But it's up to you

**Comment by sdelamo** [comment]
master also fails for me locally: 

PREDICTIVE_TEST_SELECTION=false ./gradlew clean build docs --no-build-cache --refresh-dependencies

https://ge.micronaut.io/s/d3y2wdooxv5yy

**Comment by altro3** [comment]
I'll check it tomorrow

**Comment by altro3** [comment]
@sdelamo I found the problem: just forgot clean context before test.

Fixed here: https://github.com/micronaut-projects/micronaut-openapi/pull/1448

**Pull request merged**
