### PR TITLE
Upgrade to Micronaut 3.0

### PR DESCRIPTION
**Pull request by ilopmar**
When CI passes I'll use Micronaut 2.5.9 version but still target Micronaut 3.0

### CODE REVIEW

**Comment by graemerocher** [comment]
I tested the existing release with Micronaut 3.0 snapshots and it seems to work fine

**Comment by ilopmar** [comment]
The problem of the existing release is the findbugs dependency. I did this https://github.com/micronaut-graal-tests/micronaut-basic-app/blob/3.0.x/build.gradle#L41-L42 in the GraalVM test app as a workaoround.
In this PR I remove that class so it works without adding additional dependencies to Micronaut 3.0 apps.

**Comment by ilopmar** [comment]
Ummm.... now that I think about it probably we don't need a new major version, right @graemerocher? Probably a new minor one would be enough.

**Comment by graemerocher** [comment]
yup

**Review by sdelamo — APPROVED** [review]
Please, include this in the commit message: 

- micronaut from 2.5.3 to 2.5.9
- micronaut test from 2.3.3 to 2.3.7
- swagger from 2.1.9 to 2.1.10
- fix nullability annotations
- replace javax.inject with jakarta.inject

**Pull request merged**
