### PR TITLE
Fixed additionalProperties map with `@NotEmpty` annotation

### LINKED ISSUE #1906: additionalProperties must be either a Boolean or a Schema instance (again)
### Expected Behavior

When upgrading 4.6 -> 4.7.1, we should not have the error (as fixed by https://github.com/micronaut-projects/micronaut-openapi/pull/1858)

### Actual Behaviour

When a `Map` have the jakarta `@NotEmpty` annotation, we have the error

> warning: Error:
  additionalProperties must be either a Boolean or a Schema instance
   at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: io.swagger.v3.oas.models.media.ComposedSchema["additionalProperties"]) (through reference chain: io.swagger.v3.oas.models.media.ObjectSchema["properties"]->java.util.LinkedHashMap["name"]) (through reference chain: io.swagger.v3.oas.models.OpenAPI["components"]->io.swagger.v3.oas.models.Components["schemas"]->java.util.LinkedHashMap["MyItem"])
  java.lang.IllegalArgumentException: additionalProperties must be either a Boolean or a Schema instance
   at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: io.swagger.v3.oas.models.media.ComposedSchema["additionalProperties"]) (through reference chain: io.swagger.v3.oas.models.media.ObjectSchema["properties"]->java.util.LinkedHashMap["name"]) (through reference chain: io.swagger.v3.oas.models.OpenAPI["components"]->io.swagger.v3.oas.models.Components["schemas"]->java.util.LinkedHashMap["MyItem"])
  	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:4624)
  	at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:4555)
  	at io.micronaut.openapi.visitor.OpenApiApplicationVisitor.resolvePropertyPlaceHolders(OpenApiApplicationVisitor.java:452)
warning: Error:

### Steps To Reproduce

1. Checkout demo [project](https://github.com/FrogDevelopper/micronaut-4_5)
2. Switch to branch **example/4_7**
3. Run gradle task `classes` => no issue
4. Upgrade from Micronaut 4.6.3 to Micronaut 4.7.1 in _gradle.properties_ file
5. Run gradle task `classes` => compilation fails
6. Comment the `@NotEmpy` annotation in the `java/com/frogdevelopment/MyItem.java` class
7. Run gradle task `classes` => no issue

### Environment Information

- JDK version: 21

### Example Application

https://github.com/FrogDevelopper/micronaut-4_5/tree/example/4_7

### Version

4.7.1

### PR DESCRIPTION
**Pull request by altro3**
Fixed #1906

!!! Merge it after https://github.com/micronaut-projects/micronaut-openapi/pull/1902

### CODE REVIEW

**Comment by altro3** [comment]
!!! Merge it after https://github.com/micronaut-projects/micronaut-openapi/pull/1902

**Review by graemerocher — APPROVED** [review]

**Comment by FrogDevelopper** [comment]
@sdelamo @graemerocher @altro3 
When do you think micronaut-openapi:6.13.3 including this fix can be released ?

**Comment by altro3** [comment]
@FrogDevelopper from my side - all done. I don't know what we are waiting for.

@graemerocher @sdelamo ?

PS @FrogDevelopper  next release: `6.14.0`

**Comment by FrogDevelopper** [comment]
@sdelamo , @graemerocher 
That fix is required for our project to be able to upgrade to Micronaut 4.7
Can you release micronaut-openapi-6.14.0, please ?

**Comment by altro3** [comment]
@FrogDevelopper published: https://github.com/micronaut-projects/micronaut-openapi/releases/tag/v6.14.0

**Pull request merged**
