### PR TITLE
Changed processing logic for inheritance.

### LINKED ISSUE #858: Kotlin: Some of my properties are ignored
### Expected Behavior

I have two Kotlin classes, one extends the other.

```
@Schema(name = "EntityRelationFilterWithViewDataDTO",
    description = "Filtr umožňující hledání podle cesty, fulltext hledaním, hleanim pres relations a určení výběru dat," +
            " které bude výsledný pohled obsahovat",
)
@Introspected
class EntityRelationFilterWithViewDataDTO(
    @field:Schema(hidden = true)
    val entityType: String?,
    val entitySubType: String?,
    val path: String?, val query: String?,
    @field:Schema(description = "Podmínky, které musí splňovat vazby hledaných entit (např. hledám všechnny ZOGy)")
    val relationFilters: Array<RelationFilter>? = null,
    @field:Schema(description = "Podmínky, které musí splňovat custom data entity.")
    val conditionFilters: Array<ConditionFilter>? = null,
    @field:Schema(name = "_viewDataPath",
        description = "Určení custom dat, které bude výsledný pohled obsahovat (formou path v custom data aka generich key)." +
                " Defaultně se nevrací žádná custom data, pouze základní vlastností entity.")
    val _viewDataPath: Array<String>?,
    page: Int?,
    pageSize: Int?) : FilterDTO(page, pageSize)
    
@Schema(name = "FilterDTO", description = "Obecný filtr stránkování.")
@Introspected
open class FilterDTO(
    @field:Schema(name="page", description = "Číslo stránky (pořadí), která se má vrátit", type = "integer", defaultValue = "0")
    val page: Int? = 0,
    @field:Schema(name="pageSize", description = "Velikost stránky výsledků (např. 30)", type = "integer", defaultValue = "30")
    val pageSize: Int? = 30) {
}    
```

Resulting openapi scheme should contain all these properties, expect entityType, which is hidden.

### Actual Behaviour

But this is the result. property with name starting with underscore is omited, and page and pageSize which are inherited from the parent object are missing too:

```
    EntityRelationFilterWithViewDataDTO:
      type: object
      properties:
        entitySubType:
          type: string
          nullable: true
        path:
          type: string
          nullable: true
        query:
          type: string
          nullable: true
        relationFilters:
          type: array
          description: "Podmínky, které musí splňovat vazby hledaných entit (např\
            . hledám všechnny ZOGy)"
          nullable: true
          items:
            $ref: '#/components/schemas/RelationFilter'
        conditionFilters:
          type: array
          description: "Podmínky, které musí splňovat custom data entity."
          nullable: true
          items:
            $ref: '#/components/schemas/ConditionFilter'
      description: "Filtr umožňující hledání podle cesty, fulltext hledaním, hleanim\
        \ pres relations a určení výběru dat, které bude výsledný pohled obsahovat"
```

I can see that some field:Scheme annotations are applied correctly ( `@field:Schema(hidden = true) val entityType: String? `), but some are completely ignored: `@field:Schema(name = "_viewDataPath", description = "Určení custom dat ...") val _viewDataPath: Array<String>?,`

### Steps To Reproduce

I'm trying this with:
<micronaut.version>3.7.4</micronaut.version>
<micronaut.openapi.version>4.7.1</micronaut.openapi.version>

My controller looks like this:
```
@Operation(summary = "Vrací seznam resortů daných filtrem.")
@Post("/filter")
@ContinueSpan
fun filterDepartments(@Body filterDTO: EntityRelationFilterWithViewDataDTO): HttpResponse<List<DepartmentBean?>> {
....

```

### Environment Information

_No response_

### Example Application

_No response_

### Version

3.7.4

### PR DESCRIPTION
**Pull request by altro3**
Fixed #858

### CODE REVIEW

**Comment by altro3** [comment]
@sdelamo @graemerocher Hi! Can we create different release-branch for fixes? Waiting for the release of version 4.0.0 for a very long time, and I would like to fix some bugs right now.

**Comment by altro3** [comment]
@graemerocher What about different barch for release 4.7.2 or 4.8.0 ?

**Comment by graemerocher** [comment]
There is a 4.7.x branch for 4.7.x, can you target there?

**Comment by altro3** [comment]
@graemerocher done

**Comment by graemerocher** [comment]
Thanks for the contribution!

**Pull request merged**
