### PR TITLE
Fixed problem with ref

### LINKED ISSUE #754: Schema ref is ignored
### Expected Behavior

Using a schema with a reference to an external type should include the reference verbatim in the generated output.

```java
    @ApiResponse(
        description = "success",
        content = @Content(mediaType = MediaType.APPLICATION_JSON,
                           schema = @Schema(ref = "#/components/schemas/SomethingFoo")))
```

Results in 

```yml
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SomethingFoo"
```

### Actual Behaviour

```yml
          content:
            application/json:
              schema:
                type: object
```

### Steps To Reproduce

1. Checkout the [example application](https://github.com/t-gebauer/bugreport-micronaut-openapi-schema-ref)
2. `mvn clean compile`
3. Inspect the generated OpenAPI definition: `target/classes/META-INF/swagger/bugreport-openapi-schema-ref-0.0.yml`

### Environment Information

GNU/Linux 5.15 x86_64 
openjdk 17.0.3

### Example Application

https://github.com/t-gebauer/bugreport-micronaut-openapi-schema-ref

### Version

3.5.2

### PR DESCRIPTION
**Pull request by altro3**
Add lost Callbacks annotation processing. Fixed all problems with ref parameter. Fix Header with Schema

Fixed #754

### CODE REVIEW

**Comment by graemerocher** [comment]
Needs conflicts resolving. Thanks

**Comment by altro3** [comment]
@graemerocher All conflicts resolved

**Comment by altro3** [comment]
@graemerocher Hello! Can you review the last 3 pull requests and release a new release with all the latest changes? I think after these fixes a lot of people will become happier :-)

**Comment by graemerocher** [comment]
Thanks for the contribution!@altro3 will do a release today if we can address the feedback

**Pull request merged**
