### PR TITLE
Fix generator client endpoint with single produces content type

### LINKED ISSUE #1678: Content-Type of requestBody is not added to API
### Expected Behavior

I have the following OpenAPI spec for a file upload where the upload Content-Type is defined as `application/octet-stream`

```yaml
---
openapi: 3.0.3
info:
  title: File Upload
  version: 1.0.0
tags:
  - name: files
paths:
  /:
    post:
      tags:
        - files
      summary: Upload new file to server
      operationId: uploadFile
      parameters:
        - name: X-file-crc32
          in: header
          description: Decimal CRC32B representation of the file
          required: true
          schema:
            type: string
            nullable: false
        - name: X-file-sha512
          in: header
          description: Lowercase SHA512hex representation of the file
          required: true
          schema:
            type: string
            nullable: false
        - name: X-file-size
          in: header
          description: Size of the file in bytes
          required: true
          schema:
            format: int64
            minimum: 1
            type: integer
            nullable: false
      requestBody:
        content:
          application/octet-stream:
            schema:
              format: binary
              type: string
      responses:
        "200":
          description: File was saved on server. Returns serverfilename (UUID) of
            the file.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/File'
        "202":
          description: File was already available on server. Returns serverfilename
            (UUID) of the file.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/File'
        "400":
          description: "Provided checksum, size or file was not provided or uploaded\
            \ file did not match given values"
        "401":
          description: User is not authorized to request this resource
components:
  schemas:
    File:
      type: object
      properties:
        serverFileName:
          type: string
        checksum:
          type: string
        mimeType:
          type: string
        size:
          format: int64
          type: integer
        shaHash:
          type: string
```

The upstream openapi-generator 7.7.0 generates an API with `@Consumes` and `@Produces`.

Command: `java -jar openapi-generator-cli-7.7.0.jar generate -g java-micronaut-client -o out -i files.yml`

```java
@Generated(value="org.openapitools.codegen.languages.JavaMicronautClientCodegen", date="2024-08-07T13:09:44.005819430+02:00[Europe/Berlin]", comments = "Generator version: 7.7.0")
@Client("${openapi-micronaut-client-base-path}")
public interface FilesApi {
    /**
     * Upload new file to server
     *
     * @param xFileCrc32 Decimal CRC32B representation of the file (required)
     * @param xFileSha512 Lowercase SHA512hex representation of the file (required)
     * @param xFileSize Size of the file in bytes (required)
     * @param _body  (optional)
     * @return ModelFile
     */
    @Post(uri="/")
    @Consumes({"application/json"})
    @Produces({"application/octet-stream"})
    Mono<ModelFile> uploadFile(
        @Header(name="X-file-crc32") @NotNull String xFileCrc32, 
        @Header(name="X-file-sha512") @NotNull String xFileSha512, 
        @Header(name="X-file-size") @NotNull @Min(1L) Long xFileSize, 
        @Body @Nullable File _body
    );

}
```

The upstream openapi-generator 7.6.0 also generates the same class.

### Actual Behaviour

Using the following gradle task the FilesApi is missing the `@Produces` annotation which defines the Content-Type of the request. The server responds with HTTP 415 to requests of the client.

```
micronaut {
    ...
    openapi {
        client(file("src/openapi/files.yml")) {
            apiPackageName = "com.example.files.api"
            modelPackageName = "com.example.files.model"
            clientId = "files"
            useOptional = true
            useReactive = false
            generateHttpResponseWhereRequired = true
        }
    }
}
```

```java
@Generated("io.micronaut.openapi.generator.JavaMicronautClientCodegen")
@Client("files")
public interface FilesApi {

    /**
     * {@summary Upload new file to server}
     *
     * @param xfileCrc32 Decimal CRC32B representation of the file (required)
     * @param xfileSha512 Lowercase SHA512hex representation of the file (required)
     * @param xfileSize Size of the file in bytes (required)
     * @param body (optional)
     * @return HttpResponse&lt;@Valid ModelFile&gt;
     */
    @Post("/")
    @Consumes("application/json")
    HttpResponse<@Valid ModelFile> uploadFile(
        @Header(name = "X-file-crc32") @NotNull String xfileCrc32,
        @Header(name = "X-file-sha512") @NotNull String xfileSha512,
        @Header(name = "X-file-size") @NotNull @Min(1L) Long xfileSize,
        @Body @Nullable byte[] body
    );
}
```

### Steps To Reproduce

_No response_

### Environment Information

_No response_

### Example Application

_No response_

### Version

4.4.2

### PR DESCRIPTION
**Pull request by altro3**
Fixed #1678

### CODE REVIEW

**Review by sdelamo — APPROVED** [review]

**Comment by sdelamo** [comment]
@altro3 can you resolve the conflicts?

**Comment by altro3** [comment]
@sdelamo done

**Comment by sdelamo** [comment]
@altro3 can you merge 6.12.x into this pr?

**Comment by sdelamo** [comment]
Can you merge 6.12.x into this branch?

**Comment by altro3** [comment]
done

**Comment by sdelamo** [comment]
Can your merge it again?

**Comment by altro3** [comment]
@sdelamo done

**Pull request merged**
