### PR TITLE
Add logging, if we have problems with getting beanProperties

### PR DESCRIPTION
**Pull request by altro3**
See #964

### CODE REVIEW

**Comment by altro3** [comment]
@graemerocher ping

**Comment by graemerocher** [comment]
not sure about this one, in general you shouldn't use System.out but the `VisitorContext.warn` method

**Comment by altro3** [comment]
@graemerocher oh, yes, I fix it now

**Comment by altro3** [comment]
@graemerocher Stop. And I don't use `System.out`. I use exactly `context.warn` . What's wrong?

**Comment by graemerocher** [comment]
sorry misread

**Pull request merged**
