### PR TITLE
Add support OpenAPI 3.1.0

### PR DESCRIPTION
**Pull request by altro3**
Add support OpenAPI 3.1.0 properties and objects.
Fix multiple types for OpenAPI 3.1.0.
Fix some minor bugs.
Fix process Map properties, when key is enumeration.
Code optimization

### CODE REVIEW

**Review by sdelamo — APPROVED** [review]
Please, create separate PRs in the future.

**Comment by sdelamo** [comment]
@altro3 can you merge master into this PR?

**Comment by altro3** [comment]
> Please, create separate PRs in the future.

Sorry, it's too dificult to split it now :-(

**Comment by altro3** [comment]
> @altro3 can you merge master into this PR?

done

**Pull request merged**
