### PR TITLE
Disable generator donation suggestion

### PR DESCRIPTION
**Pull request by altro3**

### CODE REVIEW

**Review by graemerocher — APPROVED** [review]

**Comment by altro3** [comment]
@graemerocher again, I can't merge it :-(

изображение

**Comment by graemerocher** [comment]
@sdelamo is the management repo overriding permissions on each sync?

**Comment by altro3** [comment]
@graemerocher could you merge all PR's and finalize release?

**Comment by sdelamo** [comment]
@altro3 can you merge 6.12.x into this PR?

@graemerocher 
> @sdelamo is the management repo overriding permissions on each sync?

I will check

**Comment by altro3** [comment]
@sdelamo done

**Pull request merged**
