### PR TITLE
Fix conversion annotations with groovy

### LINKED ISSUE #1418: Warning and missing response description when generating specs for file upload
### Expected Behavior

Response description should be present without warnings.

### Actual Behaviour

Given a controller method such as:
```groovy
    @Post(value = "/", consumes = MediaType.MULTIPART_FORM_DATA)
    @Status(HttpStatus.NO_CONTENT)
    @Operation(
            operationId = 'UploadFile',
            summary = 'Upload a file',
            requestBody = @RequestBody(
                    description = 'File request',
                    content = @Content(mediaType = MediaType.MULTIPART_FORM_DATA, schema = @Schema(type = 'object'))
            ),
            responses = [
                    @ApiResponse(responseCode = '204', description = 'OK'),
            ]
    )
    void uploadFile(CompletedFileUpload file) {
        assert file.bytes
    }
```

A warning is shown when generating the OpenAPI specs:
```
WARNING: Error converting  [{"summary":"Upload a file","operationId":"UploadFile","responses":{"204":{"description":"OK","responseCode":"204"}},"requestBody":{"description":"File request","content":{"schema":{"anyOf":[],"allOf":[],"oneOf":[],"type":"object"},"mediaType":"multipart/form-data"}}}]: to class io.swagger.v3.oas.models.Operation: Cannot construct instance of `io.swagger.v3.oas.models.media.MediaType` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('multipart/form-data')
 at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: io.swagger.v3.oas.models.Operation["requestBody"]->io.swagger.v3.oas.models.parameters.RequestBody["content"]->io.swagger.v3.oas.models.media.Content["mediaType"])
```

Although the generated specs seem to look okay, the desired description for the response is missing (might be related to the warning?):
```yml
openapi: 3.0.1
info:
  title: mn-openapi-content
  version: "0.0"
paths:
  /file:
    post:
      operationId: uploadFile # <----- Why is it uncapitalized?
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
            encoding:
              file:
                contentType: application/octet-stream
        required: true
      responses:
        "204":
          description: uploadFile 204 response # <----- this should be just 'OK'

```

 

### Steps To Reproduce

1. Download the sample project.
2. Run `./gradlew compileGroovy`
3. The warning is shown.
4. Although the specs are generated, the response description is not as expected.

### Environment Information

- Micronaut + Groovy.
- Ubuntu 22.04.
- Java 17.

### Example Application

https://github.com/tcrespog/mn-openapi-content

### Version

4.2.3

### LINKED ISSUE #1420: Empty schema for responses
### Expected Behavior

The generated `schema` field shouldn't be empty.

### Actual Behaviour

Given the following controller method:
```groovy
    @Post("/pet")
    @Operation(
            operationId = 'CreatePet',
            summary = 'Create a pet',
            requestBody = @RequestBody(description = 'Pet create request', content = @Content(schema = @Schema(implementation = CreatePetRequest))),
            responses = [
                    @ApiResponse(responseCode = '200', description = 'OK', content = @Content(schema = @Schema(implementation = CreatePetResponse))),
                    @ApiResponse(responseCode = '400', description = 'Bad request', content = @Content(schema = @Schema(implementation = ErrorResponse))),
                    @ApiResponse(responseCode = '403', description = 'Operation not allowed'),
                    @ApiResponse(responseCode = '409', description = 'Duplicated element', content = @Content(schema = @Schema(implementation = ErrorResponse)))
            ]
    )
    HttpResponse<CreatePetResponse> createPet(@Body CreatePetRequest body) {
        def respBody = new CreatePetResponse(pet: body.pet)

        return HttpResponse.ok(respBody)
    }
```

The generated specs contain empty schemas for responses:
```yml
openapi: 3.0.1
info:
  title: mn-openapi-empty-schema
  version: "0.0"
paths:
  /pet:
    post:
      summary: Create a pet
      operationId: CreatePet
      requestBody:
        description: Pet create request
        content:
          schema: {} # <----- empty schema here too, but the block below looks alright
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePetRequest'
        required: true
      responses:
        "200":
          description: OK
          content:
            schema: {} # <---- empty schema for all responses
        "400":
          description: Bad request
          content:
            schema: {}
        "403":
          description: Operation not allowed
        "409":
          description: Duplicated element
          content:
            schema: {}
components:
  schemas:
    CreatePetRequest:
      type: object
      properties:
        pet:
          $ref: '#/components/schemas/Pet'
    Pet:
      type: object
      properties:
        name:
          type: string
```

The same method in Micronaut 3.x generates something such as the following:
```yml
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreatePetResponse'
```

### Steps To Reproduce

1. Download the sample project.
2. Run `./gradlew compileGroovy`
3. In the generated specs are generated, the schema for responses is empty.

### Environment Information

- Micronaut + Groovy (and Micronaut OpenAPI 6.5.1).
- Ubuntu 22.04.
- Java 17.

### Example Application

https://github.com/tcrespog/mn-openapi-empty-schema

### Version

4.2.3

### PR DESCRIPTION
**Pull request by altro3**
Fixed #1418
Fixed #1420

### CODE REVIEW

**Comment by sdelamo** [comment]
@altro3 you have to sign the CLA again. [Sorry for the inconvenience](https://micronaut.io/2024/02/06/micronaut-contributor-license-agreement-cla-update/).

**Review by sdelamo — APPROVED** [review]

**Comment by altro3** [comment]
@sdelamo ??? What does it mean? Is this blocking the merge? What do I need to do?

**Comment by sdelamo** [comment]
> @sdelamo ??? What does it mean? Is this blocking the merge? What do I need to do?

Every contributor is required to sign a contributor license agreement. You already signed it. But we changed it (see the blog post in my previous comment for details). Because, we changed it, every contributor needs to sign it again. Click the button. It is just one minute.

**Comment by altro3** [comment]
@sdelamo yes, I understand, but I've already re-signed it . Twice

**Comment by sdelamo** [comment]
@altro3 probably a glitch with http://cla-assistant.io/ reporting. You appear as signed.

**Comment by altro3** [comment]
@sdelamo any news?

**Review by dstepanov — APPROVED** [review]

**Comment by sdelamo** [comment]
@altro3 Can you merge master into this branch?

**Comment by altro3** [comment]
@sdelamo done

**Pull request merged**
