### PR TITLE
Unwrap allOf block when it possible.

### LINKED ISSUE #1680: `@Schema` annotation on DTO field generates an OpenAPI spec with description (readOnly, requiredMode, etc) under allOf instead of on the property
### Expected Behavior

Annotating a field with `@Schema(description = "abc")` should result in the description in the generated OpenApi spec being on the component model property, the same as if the field had a JavaDoc comment.

### Actual Behaviour

The generated OpenApi spec puts the description on under `allOf`, where it can't be used by generators as the property description. Also some generators create a subclass just to hold the description, which is not at all the intended effect.

### Steps To Reproduce

```java
@Schema(description = "A simple DTO")
public class MyDto {
  @Schema(description = "A string field")
  private String field1;
  // ...
}

@Schema(description = "A DTO containing the other DTO")
public class MyDto2 {
  @Schema(description = "A field containing another DTO") // <== This description should be on the property not the nested schema
  private MyDto field2;
  // ...
}
```

generates an openapi spec with 
```yaml
components:
  schemas:
    MyDto:
      type: object
      properties:
        field1:
          type: string
          description: A string field
      description: A simple DTO
    MyDto2 :
      type: object
      properties:
        field2:
          allOf:
            - $ref: "#/components/schemas/MyDto"
            - description: A field containing another DTO
      description: A DTO containing the other DTO
```
But it should be:
```yaml
components:
  schemas:
    MyDto:
      type: object
      properties:
        field1:
          type: string
          description: A string field
      description: A simple DTO
    MyDto2 :
      type: object
      properties:
        field2:
          allOf:
            - $ref: "#/components/schemas/MyDto"
          description: A field containing another DTO
      description: A DTO containing the other DTO
```

Note that in the expected output, the description `"A field containing another DTO"` is on the property. In the first one, it's on the allOf schema.

A partial workaround is to remove the `@Schema` annotation and put the description in the JavaDoc for the field. That does generate the correct OpenApi spec in some cases but not in others.

Also, this may not be limited to just `description`. Other schema properties like `required` or `requiredMode` should also be placed on the property, not pushed under `allOf`. For example: `@Schema(requiredMode = RequiredMode.REQUIRED)`.

### Environment Information

Java 21

### Example Application

_No response_

### Version

4.4.3

### PR DESCRIPTION
**Pull request by altro3**
Fixed #1680

### CODE REVIEW

**Review by graemerocher — APPROVED** [review]

**Review by kevin-wise — APPROVED** [review]
Tested with a local build, it seems to work as intended

**Comment by kevin-wise** [comment]
Any idea when this might get merged and released? We would like to upgrade the version of the generator we use, but that depends on this fix.

**Comment by altro3** [comment]
I can't do it myselfl-  haven't rights to merge PRs

@graemerocher ping

**Comment by kevin-wise** [comment]
we will also need https://github.com/micronaut-projects/micronaut-openapi/pull/1687

**Pull request merged**
