### PR TITLE
Replace array type helper with micronaut 2.2+ API

### PR DESCRIPTION
**Pull request by rdesgroppes**
Since micronaut-core 2.2.0, `ClassElement` is equipped with a `fromArray` method we're better to use in lieu of the temporary helper that was added (#368) in order to fix the generation of multi-dimensional arrays (#367).
This removes the risk that wrong array dimensions get inadvertently used.

### CODE REVIEW

**Comment by rdesgroppes** [comment]
I'm not sure how to interpret the following CI failure:
```
Result: 109 tests run, 4 skipped, 0 failed.
Posting status 'completed' with conclusion 'success' to https://github.com/micronaut-projects/micronaut-openapi/pull/395 (sha: c4786046c149b45cd2f9854e2e2208eb9e771aeb)
Error: Resource not accessible by integration
```

**Comment by alvarosanchez** [comment]
@rdesgroppes you can disregard it, it's a known issue: https://github.com/micronaut-projects/micronaut-project-template/issues/62

**Comment by rdesgroppes** [comment]
> @rdesgroppes you can disregard it, it's a known issue: [micronaut-projects/micronaut-project-template#62](https://github.com/micronaut-projects/micronaut-project-template/issues/62)

@alvarosanchez I'm wondering how to proceed, then. Should I target another branch, for instance?

**Comment by alvarosanchez** [comment]
Don't worry, I will merge it, but wanted to release a 2.2.x version first (which I did yesterday) because this needs to go in a 2.3.x version.

**Pull request merged**
