### PR TITLE
Issue # 130 - Case 2

### PR DESCRIPTION
**Pull request by croudet**
A parameter with no annotation is considered as a PathVariable.

https://github.com/micronaut-projects/micronaut-openapi/issues/130

### CODE REVIEW

**Comment by graemerocher** [comment]
Maybe needs a test

**Comment by croudet** [comment]
Tests added.

**Comment by graemerocher** [comment]
Thanks 👍

**Comment by outersky** [comment]
@croudet Default as a PathVariable but not a  QueryValue ?

With my [test project](https://github.com/outersky/micronaut-openapi-bug-yml.git)

the correct request is :
```
curl http://localhost:8080/find1?name=outersky
```

but now [swagger-ui](http://localhost:8080/swagger)  sends a request as :

```
curl -X GET "http://localhost:8080/find1" -H "accept: application/json"
```

which will lead to an error:

```json
{
  "message": "Required argument [String name] not specified",
  "path": "/name",
  "_links": {
    "self": {
      "href": "/find1",
      "templated": false
    }
  }
}
```

**Pull request merged**
