### PR TITLE
Indicate that the swagger support does not support Groovy.

### PR DESCRIPTION
**Pull request by pmcneil**
Currently there is no indication that Swagger support does not support Groovy unless you happen to try the cli:
mn create-app my-openapi-app --features swagger-java --lang groovy
If you are trying to add swagger support to an existing groovy project it just doesn't work.

### CODE REVIEW

**Comment by graemerocher** [comment]
It does not? Wow major bug then, it should support Groovy

**Comment by graemerocher** [comment]
How did you reach the assertion that it doesn't work for Groovy?

I tried the following steps:

```
$ sdk use micronaut 1.2.2
$ mn create-app groovy-openapi --lang groovy --features swagger-groovy
$ cd groovy-openapi
$ mn create-controller foo
$ ./gradlew assemble
```

And the  Swagger YAML was generated to `build/classes/groovy/main/META-INF/swagger/groovy-openapi-0.0.yml`

**Comment by pmcneil** [comment]
on Linux:
[pmcneil@big-nerd1 micronaut]$ mn create-app my-openapi-app --features swagger-java --lang groovy
| Generating Java project...
| Warning The following features are incompatible with other feature selections and have been removed from the project
| groovy
| Application created at /home/pmcneil/devel/micronaut/my-openapi-app

**Comment by ilopmar** [comment]
@pmcneil you are using the wrong feature. It needs to be `swagger-groovy` instead of `swagger-java`

**Comment by pmcneil** [comment]
OK. Cool. so the documentation needs to point out that there is swagger-groovy exists?? I'll double check, but I couldn't see that anywhere and frankly just missed it in Graemes comment.

**Pull request closed without merging**
