### PR TITLE
Correct generating no vars classes

### PR DESCRIPTION
**Pull request by altro3**

### CODE REVIEW

**Comment by altro3** [comment]
Don't know how to create schema class without properites... But it possibly with kotlin noargs plugin. See details here: https://github.com/OpenAPITools/openapi-generator/issues/14710

**Review by sdelamo — DISMISSED** [review]
Can you add a test for this?

**Comment by altro3** [comment]
The problem is that I can't figure out in which case a class without attributes is generated. But it is definitely possible, since there is an issue. I checked it locally by forcing noArgs = true into the calculations

**Comment by altro3** [comment]
@sdelamo Tests added

**Review by graemerocher — APPROVED** [review]

**Comment by graemerocher** [comment]
Please resolve conflicts

**Comment by altro3** [comment]
@graemerocher done

**Pull request merged**
