### PR TITLE
Add processing micronaut-security configuration

### LINKED ISSUE #104: Add info about security & OpenAPI
Add info about security. How can I use `intercept-url-map` to create unsecured OpenAPI docs: https://micronaut-projects.github.io/micronaut-security/snapshot/guide/#interceptUrlMap

Example:
```
  security:
    enabled: true
    intercept-url-map:
      - pattern: /swagger/**
        access:
          - isAnonymous()
      - pattern: /swagger-ui/**
        access:
          - isAnonymous()
```

### PR DESCRIPTION
**Pull request by altro3**
Fixes #104

### CODE REVIEW

**Comment by altro3** [comment]
@graemerocher Hi! Could you review last 3 PRs?

**Comment by graemerocher** [comment]
Currently away. Will be Tuesday

**Comment by graemerocher** [comment]
@altro3 could you resolve the conflicts?

**Comment by altro3** [comment]
@graemerocher done

**Pull request merged**
