### PR TITLE
Fixed ignoring javax.validation.constraints.NotNull annotation when using @Schema

### LINKED ISSUE #660: Annotation javax.validation.constraints.NotNull ignored when using @Schema Swagger annotation
### Expected Behavior

Field should be marked as required

### Actual Behaviour

@NotNull field is not added as a required field when using @Schema annotation.
On the other side, when using Javadoc to set the description, it is correctlly marked as required. The only drawback here is that we cannot add "examples" as it is done through the Swagger annotation.

### Steps To Reproduce

1) ./gradlew classes
2) Check api-v1.0.0.yml file

### Environment Information

Micronaut 3.3.0
Java 11
macOS Monterey 12.1

### Example Application

https://github.com/jorgsant/micronaut-openapi

### Version

3.3.0

### PR DESCRIPTION
**Pull request by altro3**
Fixed #660

### CODE REVIEW

**Comment by altro3** [comment]
@ilopmar  @graemerocher Hi! I fixed several bugs and maybe we can realese these changes. Can you review them? I'm talking about these pull requests: #724, #723, #722, #721, #719, #717, #666, #606

**Comment by ilopmar** [comment]
@altro3 Hi, I'm not involved in Micronaut anymore. I'll let Graeme and the rest of the team review them. Thanks :)

**Comment by altro3** [comment]
@ilopmar Thanks! Good luck with new projects! :-)

**Comment by graemerocher** [comment]
There are test failures

**Comment by altro3** [comment]
@graemerocher thanks! all problems fixed

**Comment by graemerocher** [comment]
Thanks for the contribution!

**Pull request merged**
