### PR TITLE
Bug fixes. Add support enum annotations

### LINKED ISSUE #134: param descriptions of data model / responses are not pulled from javadocs (kotlin)
consider:

```kotlin
/**
 * @param more This property identifies if there is more content available based on the search criteria. The absence of this property means the value is false.
 * @param next This property identifies the server provided value of the next record or set of records in the paginated data set. This property ​MAY​ be populated if the ​more​ property is set to ​true.​
 * @param objects This property contains one or more STIX Objects. Objects in this list ​MUST​ be a STIX Object (e.g., SDO, SCO, SRO, Language Content object, or a Marking Definition object).
 */
@Schema(name = "envelop", description = "The envelope is a simple wrapper for STIX 2 content. When returning STIX 2 content in a TAXII response the HTTP root object payload \u200BMUST\u200B be an \u200Benvelope\u200B. This specification does not define any other form of content wrapper for objects outside of STIX content.")
data class Envelop(
        @get:Schema(description = "This property identifies if there is more content available based on the search criteria. The absence of this property means the value is false.")
        val more: Boolean = false,
        
        val next: String? = null,
        val objects: List<Map<String, Any>?> = listOf() // Is this supposed to be a null or empty list?
)
```

The `@get:Schema(description = "This property identifies if there is more content available based on the search criteria. The absence of this property means the value is false.")` had to be added for the description to be provided.  It was not "auto" pulled from the class' javadoc

### LINKED ISSUE #138: Support for JsonAnySetter/AnyGetter wrapper classes
If you have a wrapping class for a Map<String, Any>, there is no model converter to correct the object.  If you had a List<MyWrappingObject>, the swagger produced is 

```
{
   "objects": [
      {
         "myObjects": { }
      }
   ]
   }
```

where myObjects is the field in MyWrappingObject with  @JsonAnySetter and @get:JsonAnyGetter

### LINKED ISSUE #471: JsonProperty not getting picked up by yaml generation for Enum
### Task List

- [ X ] Steps to reproduce provided
- [ N/A] Stacktrace (if present) provided
- [ N/A] Example that reproduces the problem uploaded to Github
- [ X ] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create Java Enum Class with JsonProperty
```

import com.fasterxml.jackson.annotation.JsonProperty;

public enum CurrencyPair2 {
    @JsonProperty("CAD-USD") CADUSD("CAD", "USD");
    private final String baseCurrency;
    private final String quoteCurrency;

    CurrencyPair2(String baseCurrency, String quoteCurrency) {
        this.baseCurrency = baseCurrency;
        this.quoteCurrency = quoteCurrency;
    }

    public String getBaseCurrency() {
        return baseCurrency;
    }

    public String getQuoteCurrency() {
        return quoteCurrency;
    }

}

```
2. Reference class in response object/request params
3. Build OpenApi:
```

annotationProcessor("io.micronaut.openapi:micronaut-openapi")
...
implementation("io.swagger.core.v3:swagger-annotations:2.1.6")
...

```
tasks.withType(JavaCompile) {
    options.fork = true
    options.forkOptions.jvmArgs << '-Dmicronaut.openapi.views.spec=rapidoc.enabled=true,swagger-ui.enabled=true,swagger-ui.theme=flattop'
}

4. Check Swagger output

### Expected Behaviour

Enum values should be CAD-USD and serialization should convert appropriately
```
CurrencyPair2:
      type: string
      enum:
      - CAD-USD

```

### Actual Behaviour
Serialization converts on ingress and egress appropriately but enum values are CADUSD in the swagger schema
```
CurrencyPair2:
      type: string
      enum:
      - CADUSD

```

Tell us what happens instead

### Environment Information

- **Operating System**: MavOS Mojave version 10.14.6 
- **Micronaut Version:** 1.3.4
- **JDK Version:** 
- OPENAPI_VERSION=2.0.10

### Example Application

- TODO: link to github repository with example that reproduces the issue

### LINKED ISSUE #787: `@JsonProperty` name ignored in OpenAPI metadata when `@Schema` present as well
### Expected Behavior

`@JsonProperty` specified name of the field will be used in generated OpenAPI metadata

```yaml
...
components:
  schemas:
    ExampleModel:
      type: object
      properties:
        nameInJson:
          type: string
          description: example field
```

### Actual Behaviour

Class field name is used in generated OpenAPI metadata and the value in `@JsonProperty` is ignored

```yaml
...
components:
  schemas:
    ExampleModel:
      type: object
      properties:
        nameInPojo:
          type: string
          description: example field
      description: ""
```

### Steps To Reproduce

1. Controller returning simple Pojo

```java
@Controller("/api/example")
public class ExampleController {
    @Get
    public ExampleModel getExample() {
        return new ExampleModel();
    }
}
```

2. Pojo with field annotated with both @JsonProperty & @Schema

```java
@Introspected
public class ExampleModel {
    @JsonProperty("nameInJson")
    @Schema(description = "example field")
    private String nameInPojo;

    public String getNameInPojo() {
        return nameInPojo;
    }
}
```

3. Compile code which generates the OpenAPI metadata

Additional notes:
- not reproducible with `micronautVersion=3.5.4` (https://github.com/oujesky/micronaut-openapi-model-bug/blob/main/micronaut-openapi-model-bug-3.5.4.yml)
- seems to be injected with dependencies coming from `micronautVersion=3.6.0` (https://github.com/oujesky/micronaut-openapi-model-bug/blob/main/micronaut-openapi-model-bug-3.6.0.yml)
- not reproducible when `@Schema` annotation is not present on the field

### Environment Information

- Windows 10
- JDK 17

### Example Application

https://github.com/oujesky/micronaut-openapi-model-bug

### Version

3.6.0

### LINKED ISSUE #792: @Schema(type="string") does generates 'type: object' in schema file
### Expected Behavior

The following class 

`@Getter
@Setter
@Builder(builderMethodName = "of")
@Schema(name = "exemplar")
public class Exemplar
{
    @Schema(name="zone_id", type = "string")
    private ZoneId zoneId;

}
`
should generate a schema model entry of

`    ZoneId:
      type: string` 

### Actual Behaviour

I get the following 

`    ZoneId:
      type: object
      properties:
        id:
          type: string
        rules:
          $ref: '#/components/schemas/ZoneRules'`

### Steps To Reproduce

1. Pull down provided repository
2. run maven compile
3. review generated mn-schema-override-exemplar-0.0.yml

### Environment Information

- MacOS Montery 12.5 
- Ubuntu 22.04 LTS
- Java OpenJDK 17 

### Example Application

https://github.com/jmochel/mn-schema-override-exemplar

### Version

3.6.0

### PR DESCRIPTION
**Pull request by altro3**
- Added support for enum values with JsonProperty annotation (fix #471).
 - Added support JsonAnySetter annotation (fix #138)
 - Fix wrong logic for property name when used Schema and JsonProperty annotations (fix #787)
 - Fixed #134
 - Fix incorrect schema when set type for property level annotation (fixed #792)
 - Fix field javadoc properties parsing.
 - Fix invalid defaultValue and allowValues types (have always been String)
 - Fix `example` field with null value (always added `example: null` to yaml file)
 - Removed unnecessary `required: false` field in final yaml file
 - Upgrade libs:

Micronaut 3.6.1
Gradle 7.5.1
Groovy 3.0.12

### CODE REVIEW

**Comment by graemerocher** [comment]
Could you bump the minor snapshot version? Upgrading to new minors requires a minor version bump

**Comment by altro3** [comment]
@graemerocher Sure. Done

**Comment by altro3** [comment]
@graemerocher Could you merge these changes and relese them? Want to use javadoc parser on field level, but withut these changes it doesnt wotk :-(

**Comment by JouperCoding** [comment]
@altro3 Not sure if this is related, however I upgrade from Micronaut 3.4.1 -> 3.6.1 just now and in 3.4.1 the Swagger generated the .yml properly with Enum examples using the @Shchema annotation.

In 3.4.1 I had the following

```
@Schema(implementation = CloudProvider.class,
	defaultValue = "AWS",
	example = "AWS",
	description = "" +
		"Cloud Provider." +
		"\n- AWS" +
		"<br />Amazon Web Services. " +
		"\n- AZURE" +
		"<br />Microsoft Azure cloud." +
		"\n- GCP" +
		"<br />Google Cloud Platform." +
		"\n- NA" +
		"<br />Not applicable (Self hosting site)."
)
@Validated
@Introspected
//@Serdeable
public enum CloudProvider implements Serializable {

	AWS("Amazon Web Services"),
	AZURE("Microsoft Azure"),
	GCP("Google Cloud Platform"),
	NA("Not applicable");

	private String cloudProvider;

	CloudProvider(String cloudProvider) {
		this.cloudProvider = cloudProvider;
	}

	public String getCloudProvider() {
		return cloudProvider;
	}
}
```

However, after upgrading to Micronaut 3.6.1 I started to see this

```
Error converting  [{"description":"Cloud Provider.\n- AWS<br />Amazon Web Services. \n- AZURE<br />Microsoft Azure cloud.\n- GCP<br />Google Cloud Platform.\n- NA<br />Not applicable (Self hosting site).","defaultValue":"AWS","example":"AWS"}]: to class io.swagger.v3.oas.models.media.Schema: Cannot construct instance of `java.util.LinkedHashMap` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('AWS')
```

And after some testing I had to remove all defaultValue I had defined in my @Schema for ENUMs to fix above issue.

In the PR above you mention
```
Fix invalid defaultValue and allowValues types (have always been String)
Fix example field with null value (always added example: null to yaml file)
```

Why is it always added as null to the yaml file? I believe default values was working properly as strings previously?

**Comment by altro3** [comment]
@JouperCoding Hi! Ok, got it. I'll check it on the weekend

**Comment by altro3** [comment]
@JouperCoding fixed it in this PR

**Comment by graemerocher** [comment]
Sorry for the delay, was on vacation

**Comment by altro3** [comment]
@graemerocher No problem. I realized that you have a vacation according to the statistics of your activity in github ;-)

**Pull request merged**
