### PR TITLE
#392 - Improved support for @RequestBean. Ignore static fields/constants

### PR DESCRIPTION
**Pull request by mikaelvik**
I changed the test code so that it defines the name of the header using a constant, the test failed.

Ignoring static fields fixed the test.

### CODE REVIEW

**Comment by graemerocher** [comment]
Failure seems unrelated to PR

**Comment by mikaelvik** [comment]
Might be because I created the PR as a draft?

**Comment by graemerocher** [comment]
No I think something has changed in Github Actions and now forked PRs cannot write test reports

**Comment by mikaelvik** [comment]
So probably nothing for me to do to fix it :)

Any comments on the PR?

**Pull request merged**
