### PR TITLE
Added schema duplication resolution mode

### LINKED ISSUE #1698: Generated spec contains only one Schema if multiple Schema.name="xy" exist
### Feature description

Consider this situation

```kotlin
@Schema(name="Car")
data class Car1(val p1: String)

@Schema(name="Car")
data class Car2(val p2: String)
```
This will today generate a single Car schema in the openapi spec (while it seems not deterministic which of both types will be used). So one type is missing in the spec. The generated spec is valid and the generator process finishes with status ok, without any hint that some Schemas were overridden.

A similar issue was solved with #947 . But that fix only considers the name of the type and not the annotated Schema.name override.

It would be good to either:
- Generate underscore suffix (as done in #947) based on the Schema.name
- Have a configuration property to make the process error if overrides would happen

### PR DESCRIPTION
**Pull request by altro3**
Fixed #1698

Deprecated configuration properties:

`micronaut.openapi.schema-prefix`
`micronaut.openapi.schema-postfix`
`micronaut.openapi.schema`

New configuration properties to replace deprecated:

`micronaut.openapi.schema.decorator.prefix`
`micronaut.openapi.schema.decorator.postfix`
`micronaut.openapi.schema.mapping`

### CODE REVIEW

**Review by sdelamo — COMMENTED** [review]
This is a breaking change, is not it? Users upgrading with configuration keys will have to update their config.

**Comment by altro3** [comment]
@sdelamo no. Now schemas with same name renamed with index, and after this improvement, default behaviour will be the same. But I add new mode `error`, if you want to fix schema duplication manually

**Comment by altro3** [comment]
Ah... you talking about other options... So the main problem with this property: `micronaut.openapi.schema`. Need to change it, but how we can do it?

**Comment by sdelamo** [comment]
> Ah... you talking about other options... So the main problem with this property: `micronaut.openapi.schema`. Need to change it, but how we can do it?

We will have to add additional configuration options without creating a breaking change.

**Comment by altro3** [comment]
Ok, I'll fix it tomorrow

**Comment by altro3** [comment]
@sdelamo fixed

**Pull request merged**
