### PR TITLE
Add option to generate views for generated OpenApi yaml.

### PR DESCRIPTION
**Pull request by croudet**
Currently, views for swagger-ui, redoc and rapidoc are supported.

### CODE REVIEW

**Comment by graemerocher** [comment]
Thanks this looks like a useful PR. I wonder if the dependency on handlebars is necessary though.

**Comment by croudet** [comment]
The dependency is only use at compile time. But the templates are simple enough so that I can get rid of handlerbars if you want.

**Comment by graemerocher** [comment]
That would be good I think. The fewer dependencies the better, especially in annotation processor scope

**Comment by croudet** [comment]
Handlebars dependency has been removed.

**Comment by graemerocher** [comment]
Thanks this is a great PR, one thing do the docs only mention how to setup Gradle, do you know what the equivalent Maven config would be and whether that can be added to the documentation?

**Comment by croudet** [comment]
I have added the maven configuration.

**Comment by graemerocher** [comment]
Thanks for the contribution!

**Pull request merged**
