### PR TITLE
Minor improvements by swagger issues

### PR DESCRIPTION
**Pull request by altro3**
Related PRs: https://github.com/swagger-api/swagger-core/pull/4699 and https://github.com/swagger-api/swagger-core/pull/4699

### CODE REVIEW

**Review by graemerocher — APPROVED** [review]

**Comment by graemerocher** [comment]
@altro3 once approved you should be able to merge the PRs yourself

**Comment by altro3** [comment]
@graemerocher no... I can't...
изображение

**Comment by graemerocher** [comment]
hmm that is weird, one sec

**Comment by graemerocher** [comment]
@altro3 try now

**Comment by altro3** [comment]
@graemerocher yeah, now all is ok! Thanks!

**Pull request merged**
